In [70]:
import pandas as pd
pd.set_option('display.max_columns', None)

## Clean and create Master Districts Dataset

```district_master``` - This is a cleaned up list of school districts pulled together from 2013 & 2022-2025 years of data, keeping only the districts and fields that exist in all 5 years i.e. district ID, district name, county, region, and a couple of simple flags like whether it’s a charter so I can quickly see what each district.

***To-Dos / Notes***
- This needs a lot more cleaning...
- Re-title columns
- I will eventually need to re-clean this because rn It very bare bones
- I need to consider charter is not separated
- Double-check that matching district IDs actually represent the same real district across all years
- for all incoming data I will need to remove districts not in my district_final_cut 
- and if I go back more than 2022 if one of my districts in the final cut disappears then I need to remove them from the consideration to.
- 

i.e. 
a district is not listed for any number of reasons before 2019 but in my current list of districts from 2022-2025 if i used data back to 2014 then it will skew... actually I just loaded in 2012 and added that to the set cross refrence and it narrowd down the list a little more so im just going with those ones.

In [71]:
# Load in District data
district_2025 = pd.read_csv(r'District Infromation\2025 District Reference.csv')
district_2024 = pd.read_csv(r'District Infromation\2024 District Reference.csv')
district_2023 = pd.read_csv(r'District Infromation\2023 District Reference Information.csv')
district_2022 = pd.read_csv(r'District Infromation\2022 District Reference Information, Accountability Rating and Special Education Determination Status.csv')
district_2013 = pd.read_csv(r'District Infromation/2013 District Reference .dat', dtype=str)

In [72]:
district_25_headers = district_2025.iloc[0]
district_25 = district_2025[1:]
district_25.columns = district_25_headers
district_25.insert(loc=0, column="Year", value="2025")

district_25.head(1)

,Year,DISTRICT,DISTNAME,COUNTY,CNTYNAME,REGION,REGNNAME,DFLCHART,DFLALTED,D_RATING,DAD_POST,ASVAB_STATUS,OUTCOME
1,2025,001902,CAYUGA ISD,001,ANDERSON,07,REGION 07: KILGORE,N,N,B,1,,Meets Requirements

In [73]:
district_2024_headers = district_2024.iloc[0]
district_24 = district_2024[1:]
district_24.columns = district_2024_headers
district_24.insert(loc=0, column="Year", value="2024")

district_24.head(1)

,Year,DISTRICT,DISTNAME,COUNTY,CNTYNAME,REGION,REGNNAME,DFLCHART,DFLALTED,D_RATING,DAD_POST,ASVAB_STATUS,OUTCOME
1,2024,001902,CAYUGA ISD,001,ANDERSON,07,REGION 07: KILGORE,N,N,B,1,,Meets Requirements

In [74]:
district_2022

,COUNTY,REGION,DISTRICT,D_rating,DISTNAME,CNTYNAME,DFLCHART,DFLALTED,DAD_POST,OUTCOME,asvab_status
0,'001,'07,'001902,A,CAYUGA ISD,ANDERSON,N,N,1,Meets Requirements,
1,'001,'07,'001903,A,ELKHART ISD,ANDERSON,N,N,0,Meets Requirements,
2,'001,'07,'001904,A,FRANKSTON ISD,ANDERSON,N,N,0,Meets Requirements,ASVAB Alternative Test Offered
3,'001,'07,'001906,A,NECHES ISD,ANDERSON,N,N,1,Meets Requirements,
4,'001,'07,'001907,B,PALESTINE ISD,ANDERSON,N,N,0,Needs Assistance,
...,...,...,...,...,...,...,...,...,...,...,...
1202,'252,'09,'252902,A,NEWCASTLE ISD,YOUNG,N,N,,Meets Requirements,
1203,'252,'09,'252903,A,OLNEY ISD,YOUNG,N,N,0,Meets Requirements,
1204,'253,'01,'253901,B,ZAPATA COUNTY ISD,ZAPATA,N,N,0,Needs Assistance,
1205,'254,'20,'254901,B,CRYSTAL CITY ISD,ZAVALA,N,N,0,Needs Intervention,
1206,'254,'20,'254902,B,LA PRYOR ISD,ZAVALA,N,N,0,Meets Requirements,

In [75]:
district_2022

,COUNTY,REGION,DISTRICT,D_rating,DISTNAME,CNTYNAME,DFLCHART,DFLALTED,DAD_POST,OUTCOME,asvab_status
0,'001,'07,'001902,A,CAYUGA ISD,ANDERSON,N,N,1,Meets Requirements,
1,'001,'07,'001903,A,ELKHART ISD,ANDERSON,N,N,0,Meets Requirements,
2,'001,'07,'001904,A,FRANKSTON ISD,ANDERSON,N,N,0,Meets Requirements,ASVAB Alternative Test Offered
3,'001,'07,'001906,A,NECHES ISD,ANDERSON,N,N,1,Meets Requirements,
4,'001,'07,'001907,B,PALESTINE ISD,ANDERSON,N,N,0,Needs Assistance,
...,...,...,...,...,...,...,...,...,...,...,...
1202,'252,'09,'252902,A,NEWCASTLE ISD,YOUNG,N,N,,Meets Requirements,
1203,'252,'09,'252903,A,OLNEY ISD,YOUNG,N,N,0,Meets Requirements,
1204,'253,'01,'253901,B,ZAPATA COUNTY ISD,ZAPATA,N,N,0,Needs Assistance,
1205,'254,'20,'254901,B,CRYSTAL CITY ISD,ZAVALA,N,N,0,Needs Intervention,
1206,'254,'20,'254902,B,LA PRYOR ISD,ZAVALA,N,N,0,Meets Requirements,

In [76]:
# Strip the leading ' in front of County, Region, District (most likely there due to excel being common for analysis and it would keep those as strings not ints)
district_2022['COUNTY'] = district_2022['COUNTY'].str[1:]
district_2022['REGION'] = district_2022['REGION'].str[1:]
district_2022['DISTRICT'] = district_2022['DISTRICT'].str[1:]

district_2023['COUNTY'] = district_2023['COUNTY'].str[1:]
district_2023['REGION'] = district_2023['REGION'].str[1:]
district_2023['DISTRICT'] = district_2023['DISTRICT'].str[1:]

In [77]:
# Add years as a column
district_2013.insert(loc=0, column="Year", value="2013")
district_2022.insert(loc=0, column="Year", value="2022")
district_2023.insert(loc=0, column="Year", value="2023")

district_22 = district_2022
district_23 = district_2023

In [78]:
# This is a cleaned list of school districts I’m keeping by taking only the districts that show up in every dataset (2025, 2024, 2023, 2022, and 2013), 
# based on the assumption that if a district ID exists across all years, it’s stable enough to trust and include.

# To-do: Double-check that matching district IDs actually represent the same real district across all years
d_25 = set(district_25['DISTRICT'])
d_24 = set(district_24['DISTRICT'])
d_23 = set(district_23['DISTRICT'])
d_22 = set(district_22['DISTRICT'])
d_12 = set(district_2013['DISTRICT'])

# Creating a set of districts only in all
District_final_cut = d_25 & d_24 & d_23 & d_22 & d_12
District_final_cut
len(District_final_cut)

1162

In [79]:
# Check district lengths aren't changing  
# 2025: Original List Len: 1208 New List Len: 1208
# 2024: Original List Len: 1207 New List Len: 1207
# 2023: Original List Len: 1209 New List Len: 1209
# 2022: Original List Len: 1207 New List Len: 1207

print(f'Original List Len: {len(district_22['DISTRICT'])} New Set Len: {len(d_22)}')

Original List Len: 1207 New Set Len: 1207

In [80]:
def remove_districts(districts):
    filter = districts['DISTRICT'].isin(District_final_cut)
    filtered_district = districts[filter]
    return filtered_district

In [81]:
district_25_filtered = remove_districts(district_25)
district_24_filtered = remove_districts(district_24)
district_23_filtered = remove_districts(district_23)
district_22_filtered = remove_districts(district_22)
district_13_filtered = remove_districts(district_2013)

In [82]:
dist_25_col = set(district_25_filtered.columns)
dist_24_col = set(district_24_filtered.columns)
dist_23_col = set(district_23_filtered.columns)
dist_22_col = set(district_22_filtered.columns)
dist_13_col = set(district_2013.columns)

dist_col_in_all = dist_25_col & dist_24_col & dist_23_col & dist_22_col & dist_13_col
dist_col_in_all

{'CNTYNAME',
 'COUNTY',
 'DFLALTED',
 'DFLCHART',
 'DISTNAME',
 'DISTRICT',
 'REGION',
 'Year'}

In [83]:
# now I need to make a new data frame that is a version of all of these where all the data is the same, and I want to see what wrong with the ones that arent.
# i.e. if a cdn is around an but the district name is diff or county etc

dist_df_list = [district_25_filtered, district_24_filtered, district_23_filtered, district_22_filtered, district_13_filtered]

districts_grouped = pd.concat(
    [df.loc[:, df.columns.intersection(dist_col_in_all)] for df in dist_df_list]   
)

districts_grouped

,Year,DISTRICT,DISTNAME,COUNTY,CNTYNAME,REGION,DFLCHART,DFLALTED
1,2025,001902,CAYUGA ISD,001,ANDERSON,07,N,N
2,2025,001903,ELKHART ISD,001,ANDERSON,07,N,N
3,2025,001904,FRANKSTON ISD,001,ANDERSON,07,N,N
4,2025,001906,NECHES ISD,001,ANDERSON,07,N,N
5,2025,001907,PALESTINE ISD,001,ANDERSON,07,N,N
...,...,...,...,...,...,...,...,...
1223,2013,252902,NEWCASTLE ISD,252,YOUNG,09,N,N
1224,2013,252903,OLNEY ISD,252,YOUNG,09,N,N
1225,2013,253901,ZAPATA COUNTY ISD,253,ZAPATA,01,N,N
1226,2013,254901,CRYSTAL CITY ISD,254,ZAVALA,20,N,N
1227,2013,254902,LA PRYOR ISD,254,ZAVALA,20,N,N

In [84]:
dist_df_list

[0     Year DISTRICT           DISTNAME COUNTY  CNTYNAME REGION  \
 1     2025   001902         CAYUGA ISD    001  ANDERSON     07
 2     2025   001903        ELKHART ISD    001  ANDERSON     07
 3     2025   001904      FRANKSTON ISD    001  ANDERSON     07
 4     2025   001906         NECHES ISD    001  ANDERSON     07
 5     2025   001907      PALESTINE ISD    001  ANDERSON     07
 ...    ...      ...                ...    ...       ...    ...
 1204  2025   252902      NEWCASTLE ISD    252     YOUNG     09
 1205  2025   252903          OLNEY ISD    252     YOUNG     09
 1206  2025   253901  ZAPATA COUNTY ISD    253    ZAPATA     01
 1207  2025   254901   CRYSTAL CITY ISD    254    ZAVALA     20
 1208  2025   254902       LA PRYOR ISD    254    ZAVALA     20

 0                     REGNNAME DFLCHART DFLALTED D_RATING DAD_POST  \
 1           REGION 07: KILGORE        N        N        B        1
 2           REGION 07: KILGORE        N        N        B        0
 3           REGION 07: KILGORE        N        N        B        1
 4           REGION 07: KILGORE        N        N        A        0
 5           REGION 07: KILGORE        N        N        C        0
 ...                        ...      ...      ...      ...      ...
 1204  REGION 09: WICHITA FALLS        N        N        A
 1205  REGION 09: WICHITA FALLS        N        N        B        1
 1206       REGION 01: EDINBURG        N        N        B        0
 1207    REGION 20: SAN ANTONIO        N        N        D        0
 1208    REGION 20: SAN ANTONIO        N        N        D        0

 0                       ASVAB_STATUS             OUTCOME
 1                                     Meets Requirements
 2                                     Meets Requirements
 3     ASVAB Alternative Test Offered  Meets Requirements
 4                                     Meets Requirements
 5                                       Needs Assistance
 ...                              ...                 ...
 1204                                  Meets Requirements
 1205                                  Meets Requirements
 1206                                    Needs Assistance
 1207                                  Needs Intervention
 1208                                  Meets Requirements

 [1162 rows x 13 columns],
 0     Year DISTRICT           DISTNAME COUNTY  CNTYNAME REGION  \
 1     2024   001902         CAYUGA ISD    001  ANDERSON     07
 2     2024   001903        ELKHART ISD    001  ANDERSON     07
 3     2024   001904      FRANKSTON ISD    001  ANDERSON     07
 4     2024   001906         NECHES ISD    001  ANDERSON     07
 5     2024   001907      PALESTINE ISD    001  ANDERSON     07
 ...    ...      ...                ...    ...       ...    ...
 1203  2024   252902      NEWCASTLE ISD    252     YOUNG     09
 1204  2024   252903          OLNEY ISD    252     YOUNG     09
 1205  2024   253901  ZAPATA COUNTY ISD    253    ZAPATA     01
 1206  2024   254901   CRYSTAL CITY ISD    254    ZAVALA     20
 1207  2024   254902       LA PRYOR ISD    254    ZAVALA     20

 0                     REGNNAME DFLCHART DFLALTED D_RATING DAD_POST  \
 1           REGION 07: KILGORE        N        N        B        1
 2           REGION 07: KILGORE        N        N        B        0
 3           REGION 07: KILGORE        N        N        B        1
 4           REGION 07: KILGORE        N        N        B        0
 5           REGION 07: KILGORE        N        N        B        0
 ...                        ...      ...      ...      ...      ...
 1203  REGION 09: WICHITA FALLS        N        N        B
 1204  REGION 09: WICHITA FALLS        N        N        B        1
 1205       REGION 01: EDINBURG        N        N        C        0
 1206    REGION 20: SAN ANTONIO        N        N        D        0
 1207    REGION 20: SAN ANTONIO        N        N        D        0

 0                       ASVAB_STATUS             OUTCOME
 1                                     Meets Requirements
 2                                     Meets Requirements
 3     ASVAB Alternative Test Offered  Meets Requirements
 4                                     Meets Requirements
 5                                       Needs Assistance
 ...                              ...                 ...
 1203                                  Meets Requirements
 1204                                  Meets Requirements
 1205                                  Meets Requirements
 1206                                  Needs Intervention
 1207                                  Meets Requirements

 [1162 rows x 13 columns],
       Year COUNTY REGION DISTRICT           DISTNAME  CNTYNAME DFLCHART  \
 0     2023    001     07   001902         CAYUGA ISD  ANDERSON        N
 1     2023    001     07   001903        ELKHART ISD  ANDERSON        N
 2     2023    001     07   001904      FRANKSTON ISD  ANDERSON        N
 3     2023    001     07   001906         NECHES ISD  ANDERSON        N
 4     2023    001     07   001907      PALESTINE ISD  ANDERSON        N
 ...    ...    ...    ...      ...                ...       ...      ...
 1204  2023    252     09   252902      NEWCASTLE ISD     YOUNG        N
 1205  2023    252     09   252903          OLNEY ISD     YOUNG        N
 1206  2023    253     01   253901  ZAPATA COUNTY ISD    ZAPATA        N
 1207  2023    254     20   254901   CRYSTAL CITY ISD    ZAVALA        N
 1208  2023    254     20   254902       LA PRYOR ISD    ZAVALA        N

      DFLALTED                    ASVAB_STATUS
 0           N
 1           N
 2           N  ASVAB Alternative Test Offered
 3           N
 4           N
 ...       ...                             ...
 1204        N
 1205        N
 1206        N
 1207        N
 1208        N

 [1162 rows x 9 columns],
       Year COUNTY REGION DISTRICT D_rating           DISTNAME  CNTYNAME  \
 0     2022    001     07   001902        A         CAYUGA ISD  ANDERSON
 1     2022    001     07   001903        A        ELKHART ISD  ANDERSON
 2     2022    001     07   001904        A      FRANKSTON ISD  ANDERSON
 3     2022    001     07   001906        A         NECHES ISD  ANDERSON
 4     2022    001     07   001907        B      PALESTINE ISD  ANDERSON
 ...    ...    ...    ...      ...      ...                ...       ...
 1202  2022    252     09   252902        A      NEWCASTLE ISD     YOUNG
 1203  2022    252     09   252903        A          OLNEY ISD     YOUNG
 1204  2022    253     01   253901        B  ZAPATA COUNTY ISD    ZAPATA
 1205  2022    254     20   254901        B   CRYSTAL CITY ISD    ZAVALA
 1206  2022    254     20   254902        B       LA PRYOR ISD    ZAVALA

      DFLCHART DFLALTED DAD_POST             OUTCOME  \
 0           N        N        1  Meets Requirements
 1           N        N        0  Meets Requirements
 2           N        N        0  Meets Requirements
 3           N        N        1  Meets Requirements
 4           N        N        0    Needs Assistance
 ...       ...      ...      ...                 ...
 1202        N        N           Meets Requirements
 1203        N        N        0  Meets Requirements
 1204        N        N        0    Needs Assistance
 1205        N        N        0  Needs Intervention
 1206        N        N        0  Meets Requirements

                         asvab_status
 0
 1
 2     ASVAB Alternative Test Offered
 3
 4
 ...                              ...
 1202
 1203
 1204
 1205
 1206

 [1162 rows x 12 columns],
       Year DISTRICT  CNTYNAME COUNTY DFLALTED DFLCHART           DISTNAME  \
 0     2013   001902  ANDERSON    001        N        N         CAYUGA ISD
 1     2013   001903  ANDERSON    001        N        N        ELKHART ISD
 2     2013   001904  ANDERSON    001        N        N      FRANKSTON ISD
 3     2013   001906  ANDERSON    001        N        N         NECHES ISD
 4     2013   001907  ANDERSON    001        N        N      PALESTINE ISD
 ...    ...      ...       ...    ...      ...      ...                ...
 1223  2013   252902     YOUNG    252        N        N      NEWCASTLE ISD
 1224  2013   252903     YOUNG    252        N        N          OLNEY ISD
 1225  2013   253901    ZAPATA    253        N        N  ZAPATA COUNTY ISD
 1226  2013   254901    ZAVALA    254        N        N   CRYSTAL CITY ISD
 1227  2013   254902    ZAVALA    254        N        N       LA PRYOR ISD

      D_RATING REGION SECS
 0           M     07
 1           M     07
 2           M     07    D
 3           M     07
 4           M     07
 ...       ...    ...  ...
 1223        M     09
 1224        M     09
 1225        M     01    B
 1226        I     20    H
 1227        M     20    L

 [1162 rows x 10 columns]]

In [85]:
# Check how many unique 'charter_status' values each district has
charter_check = districts_grouped.groupby('DISTRICT')['DFLALTED'].nunique()

aea_check = districts_grouped.groupby('DISTRICT')['DFLALTED'].nunique()

# IDs where the status changed (more than 1 unique value)
# inconsistent_ids = charter_check[charter_check > 1].index  # Nothing
inconsistent_ids = aea_check[aea_check > 1].index
inconsistent_ids

Index(['015807', '015808', '101804', '101837', '101842', '101864', '193801'], dtype='str', name='DISTRICT')

In [86]:
districts_grouped.shape

districts_cleaned = districts_grouped[~districts_grouped['DISTRICT'].isin(inconsistent_ids)]

print(districts_grouped.shape, districts_cleaned.shape)

(5810, 8) (5775, 8)

In [87]:
districts_cleaned

,Year,DISTRICT,DISTNAME,COUNTY,CNTYNAME,REGION,DFLCHART,DFLALTED
1,2025,001902,CAYUGA ISD,001,ANDERSON,07,N,N
2,2025,001903,ELKHART ISD,001,ANDERSON,07,N,N
3,2025,001904,FRANKSTON ISD,001,ANDERSON,07,N,N
4,2025,001906,NECHES ISD,001,ANDERSON,07,N,N
5,2025,001907,PALESTINE ISD,001,ANDERSON,07,N,N
...,...,...,...,...,...,...,...,...
1223,2013,252902,NEWCASTLE ISD,252,YOUNG,09,N,N
1224,2013,252903,OLNEY ISD,252,YOUNG,09,N,N
1225,2013,253901,ZAPATA COUNTY ISD,253,ZAPATA,01,N,N
1226,2013,254901,CRYSTAL CITY ISD,254,ZAVALA,20,N,N
1227,2013,254902,LA PRYOR ISD,254,ZAVALA,20,N,N

In [88]:
# using 2025 as source of truth

district_master = districts_cleaned[districts_cleaned["Year"]=='2025'].reset_index(drop=True)


district_master.head()

   Year DISTRICT       DISTNAME COUNTY  CNTYNAME REGION DFLCHART DFLALTED
0  2025   001902     CAYUGA ISD    001  ANDERSON     07        N        N
1  2025   001903    ELKHART ISD    001  ANDERSON     07        N        N
2  2025   001904  FRANKSTON ISD    001  ANDERSON     07        N        N
3  2025   001906     NECHES ISD    001  ANDERSON     07        N        N
4  2025   001907  PALESTINE ISD    001  ANDERSON     07        N        N

In [89]:
district_master.columns = ['Year', 'District ID', 'District Name', 'County ID', 'County Name', 'Region', 'Charter Flag', 'DFLALTED']
district_master.head(2)

,Year,District ID,District Name,County ID,County Name,Region,Charter Flag,DFLALTED
0,2025,001902,CAYUGA ISD,001,ANDERSON,07,N,N
1,2025,001903,ELKHART ISD,001,ANDERSON,07,N,N

## Clean Student & Staff Datasets

```staff_master``` - This is all staff data from 2013 through 2025 merged the same way, with only the shared columns kept so everything lines up cleanly year to year.

```student_master``` - This is all student data from 2013 through 2025 merged together, keeping only the columns that exist in every year so the data is consistent across time.

***To-Dos / Notes***
- This needs a lot more cleaning...
- Account for any data masking (haven't handled that yet)
- Add testing and validation throughout the process to validate each step.
- Clean up the keys table, to account for columns that are the same thing but named differently depending on the yea, handle fields that only exist in some years but are still useful.

***Useful links***
- View had data is masked: https://rptsvr1.tea.texas.gov/perfreport/tapr/2025/masking.html (change year value 2013-2025)
- 2013 data download headers explained: https://rptsvr1.tea.texas.gov/perfreport/tapr/2013/download/taprref.html

In [90]:
# Load in all staff data
StudentStaff_Info_2013 = pd.read_csv(r"Staff & Student Data\2013 Staff & Student Information.txt", dtype=str)
StudentStaff_Info_2014 = pd.read_csv(r"Staff & Student Data\2014 Staff & Student Information.dat", dtype=str)
StudentStaff_Info_2015 = pd.read_csv(r"Staff & Student Data\2015 Staff & Student Information.dat", dtype=str)
StudentStaff_Info_2016 = pd.read_csv(r"Staff & Student Data\2016 District Staff & Student Information.dat", dtype=str)
StudentStaff_Info_2017 = pd.read_csv(r"Staff & Student Data\2017 Staff & Student Information.dat", dtype=str)
StudentStaff_Info_2018 = pd.read_csv(r"Staff & Student Data\2018 Staff, Student, and Annual Graduates.dat", dtype=str)
StudentStaff_Info_2019 = pd.read_csv(r"Staff & Student Data\2019 Staff, Student, and Annual Graduates.dat", dtype=str)
StudentStaff_Info_2020 = pd.read_csv(r"Staff & Student Data\2020 Staff, Student, and Annual Graduates.dat", dtype=str)
StudentStaff_Info_2021 = pd.read_csv(r"Staff & Student Data\2021 Staff, Student, and Annual Graduates.csv", dtype=str)
StudentStaff_Info_2022 = pd.read_csv(r"Staff & Student Data\2022 Staff, Student, and Annual Graduates.csv", dtype=str)
StudentStaff_Info_2023 = pd.read_csv(r"Staff & Student Data\2023 Staff, Student, and Annual Graduates.csv", dtype=str)
Student_Info_2024 = pd.read_csv(r"Staff & Student Data\2024 District Student Information.csv", dtype=str)
Staff_Info_2024 = pd.read_csv(r"Staff & Student Data\2024 District Staff Information.csv", dtype=str)
Student_Info_2025 = pd.read_csv(r"Staff & Student Data\2025 District Student Information.csv", dtype=str)
Staff_Info_2025 = pd.read_csv(r"Staff & Student Data\2025 District Staff Information.csv", dtype=str)

### Seprate Student and Staff Data 2013 - 2023

- When I downloaded the datasets for student and staff information 2013 and 2023 the student staff data was combined. I will want to separate these later but to make managing this many tables scalable I will throw then in a dict. ```Note: I will add 2024 and 2025 separated student and staff DataFrames to a dictionary later.```
- Load in the student staff key files

Future Goal: Combining all student and staff data downloads in master keys based on all unique rows but i think a function will be quicker for me to do now so I'll merge the headers later

In [91]:
# Add student and staff 2013 and 2023 combined dataframes to a dictionary.

student_staff_dfs = {2013:StudentStaff_Info_2013, 
                      2014:StudentStaff_Info_2014, 
                      2015:StudentStaff_Info_2015, 
                      2016:StudentStaff_Info_2016, 
                      2017:StudentStaff_Info_2017,
                      2018:StudentStaff_Info_2018,
                      2019:StudentStaff_Info_2019, 
                      2020:StudentStaff_Info_2020,
                      2021:StudentStaff_Info_2021,
                      2022:StudentStaff_Info_2022,
                      2023:StudentStaff_Info_2023}
type(student_staff_dfs)

dict

In [92]:
# Loading in all the student and staff keys for 2013 to 2024
student_key_tables ={}
staff_key_tables = {}

for year in range(2013, 2024):
    # Load in files with a year variable
    student_key = pd.read_csv(rf"Staff & Student Keys\{year}_TAPR_Advanced_Data_Download_Student.csv")
    staff_key = pd.read_csv(rf"Staff & Student Keys\{year}_TAPR_Advanced_Data_Download_Staff.csv")

    student_key_tables[year] = student_key
    staff_key_tables[year] = staff_key

print(len(student_key_tables), len(staff_key_tables))

11 11

In [93]:
# For the 2024 and 2025 school years, data sets had the header a human readable name I stripped that for now and promoted index 0 which used the old id naming conversion

# Note: I'll eventually need to save those header
def PromoteFirstRow(df, year):  
    new_headers = df.iloc[0]
    new_df = df.iloc[1:]
    new_df.columns = new_headers
    new_df = new_df.reset_index(drop=True)
    key_df = pd.DataFrame(new_headers)
    key_df = key_df.reset_index()
    key_df.columns = ["LABEL", "NAME"]

    return new_df, key_df

Student_Info_2024, key_df_stu_24 = PromoteFirstRow(Student_Info_2024, 2024)
student_key_tables[2024] = key_df_stu_24

Student_Info_2025, key_df_stu_25= PromoteFirstRow(Student_Info_2025, 2025)
student_key_tables[2025] = key_df_stu_25

Staff_Info_2024, key_df_staff_24= PromoteFirstRow(Staff_Info_2024, 2024)
staff_key_tables[2024] = key_df_staff_24

Staff_Info_2025, key_df_staff_25= PromoteFirstRow(Staff_Info_2025, 2025)
staff_key_tables[2025] = key_df_staff_25

In [94]:
# Creating two dictionary one holding all the student data another holding all the staff data 

student_tables = {}
staff_tables = {}

for year in range(2013, 2024):
    # In the dictionary student_tables we have {year: DataFrame} i want to copy the data from the respective 


    student_tables[year] = student_staff_dfs[year][student_key_tables[year]['NAME']].copy()
    staff_tables[year] = student_staff_dfs[year][staff_key_tables[year]['NAME']].copy()

    student_tables[year].insert(loc=0, column="Year", value=year)
    staff_tables[year].insert(loc=0, column="Year", value=year)

    if year == 2023:

        
        student_tables[2024] = Student_Info_2024
        student_tables[2025] = Student_Info_2025
        student_tables[2024].insert(loc=0, column="Year", value=2024)
        student_tables[2025].insert(loc=0, column="Year", value=2025)

        staff_tables[2024] = Staff_Info_2024
        staff_tables[2025] = Staff_Info_2025
        staff_tables[2024].insert(loc=0, column="Year", value=2024)
        staff_tables[2025].insert(loc=0, column="Year", value=2025)

# Removing the ' character from districts column, likely put there for when excel was used to know the field was a string
staff_tables[2021]['DISTRICT'] = staff_tables[2021]['DISTRICT'] .str[1:]
staff_tables[2022]['DISTRICT'] = staff_tables[2022]['DISTRICT'] .str[1:]
staff_tables[2023]['DISTRICT'] = staff_tables[2023]['DISTRICT'] .str[1:]

student_tables[2021]['DISTRICT'] = student_tables[2021]['DISTRICT'] .str[1:]
student_tables[2022]['DISTRICT'] = student_tables[2022]['DISTRICT'] .str[1:]
student_tables[2023]['DISTRICT'] = student_tables[2023]['DISTRICT'] .str[1:]

In [95]:
# doing a basic test to see if the shapes make sense not sure why its plus one but not worries enough to check rn... i feel like it something to do with counting a header or index
for i in range(2013, 2024):    
    print(f"[{i}]: New Shape: {staff_tables[i].shape}, Expected shape: ({student_staff_dfs[i].shape[0]}, {staff_key_tables[i].shape[0]})")

[2013]: New Shape: (1228, 138), Expected shape: (1228, 137)
[2014]: New Shape: (1227, 138), Expected shape: (1227, 137)
[2015]: New Shape: (1219, 138), Expected shape: (1219, 137)
[2016]: New Shape: (1207, 138), Expected shape: (1207, 137)
[2017]: New Shape: (1203, 151), Expected shape: (1203, 150)
[2018]: New Shape: (1200, 155), Expected shape: (1200, 154)
[2019]: New Shape: (1201, 155), Expected shape: (1201, 154)
[2020]: New Shape: (1202, 116), Expected shape: (1202, 115)
[2021]: New Shape: (1204, 121), Expected shape: (1204, 120)
[2022]: New Shape: (1207, 127), Expected shape: (1207, 126)
[2023]: New Shape: (1209, 121), Expected shape: (1209, 120)

#### Current Data State (Checkpoint)

```student_tables = {}```

```staff_tables = {}```

```student_key_tables ={}```

```staff_key_tables = {}```

Note: *If comparing the data shown from this year’s report to, previous reports, use the data displayed under Membership.* [Source](https://tea.texas.gov/texas-schools/accountability/academic-accountability/performance-reporting/2020-profile-glossary.pdf)

In [ ]:
oldKeyShapes = {}
newKeyShapes = {}

bad_strings = ['Percent', 'Rate', 'Ratio', '%', 'Enrollment']
pattern = "|".join(bad_strings)

for year in range(2013, 2026):
    """
    remove columns we do not want to even looking at from dictionary, i.e. the one listed in bad_strings list. 
    most of the code in this block is to make the pretty output at the bottom. only 2 lines in here do the work
    
    student_key_tables[year] = student_key_tables[year][~student_key_tables[year]["LABEL"].str.contains(pattern, na=False)]
    student_key_tables[year] = student_key_tables[year].reset_index(drop=True)
    
    """
    # store old shapes (before filtering)
    oldKeyShapes[year] = {
        "student": student_key_tables[year].shape,
        "staff": staff_key_tables[year].shape
    }

    student_key_tables[year] = student_key_tables[year][~student_key_tables[year]["LABEL"].str.contains(pattern, na=False)]
    staff_key_tables[year] = staff_key_tables[year][~staff_key_tables[year]["LABEL"].str.contains(pattern, na=False)]

    student_key_tables[year] = student_key_tables[year].reset_index(drop=True)
    staff_key_tables[year] = staff_key_tables[year].reset_index(drop=True)
    # store new shapes (after filtering)
    newKeyShapes[year] = {
        "student": student_key_tables[year].shape,
        "staff": staff_key_tables[year].shape
    }

    # unpack for readability
    old_student, old_staff = oldKeyShapes[year]["student"], oldKeyShapes[year]["staff"]
    new_student, new_staff = newKeyShapes[year]["student"], newKeyShapes[year]["staff"]

    # compute reductions
    student_diff = old_student[0] - new_student[0]
    staff_diff = old_staff[0] - new_staff[0]

    print(
        f"{year} | "
        f"Student Keys: {old_student} → {new_student} (−{student_diff}) | "
        f"Staff Keys: {old_staff} → {new_staff} (−{staff_diff})"
    )

2013 | Student Keys: (51, 4) → (51, 4) (−0) | Staff Keys: (100, 4) → (100, 4) (−0)
2014 | Student Keys: (51, 4) → (51, 4) (−0) | Staff Keys: (100, 4) → (100, 4) (−0)
2015 | Student Keys: (52, 4) → (52, 4) (−0) | Staff Keys: (100, 4) → (100, 4) (−0)
2016 | Student Keys: (55, 4) → (55, 4) (−0) | Staff Keys: (100, 4) → (100, 4) (−0)
2017 | Student Keys: (61, 4) → (61, 4) (−0) | Staff Keys: (113, 4) → (113, 4) (−0)
2018 | Student Keys: (44, 4) → (44, 4) (−0) | Staff Keys: (117, 4) → (117, 4) (−0)
2019 | Student Keys: (46, 4) → (46, 4) (−0) | Staff Keys: (117, 4) → (117, 4) (−0)
2020 | Student Keys: (95, 4) → (95, 4) (−0) | Staff Keys: (78, 4) → (78, 4) (−0)
2021 | Student Keys: (149, 4) → (149, 4) (−0) | Staff Keys: (82, 4) → (82, 4) (−0)
2022 | Student Keys: (111, 4) → (111, 4) (−0) | Staff Keys: (88, 4) → (88, 4) (−0)
2023 | Student Keys: (149, 4) → (149, 4) (−0) | Staff Keys: (82, 4) → (82, 4) (−0)
2024 | Student Keys: (78, 2) → (78, 2) (−0) | Staff Keys: (82, 2) → (82, 2) (−0)
2025 | Student Keys: (79, 2) → (79, 2) (−0) | Staff Keys: (82, 2) → (82, 2) (−0)

Having difficulty understanding why the student count appears in 2023 data

In [114]:
staff_17 = staff_key_tables[2017]

In [115]:
staff_24 = staff_key_tables[2024]

In [116]:
student_17 = student_key_tables[2017]
student_24 = student_key_tables[2024]